/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "client-go/k8s-client-go/pkg/apis/dummy/v1alpha1"
	scheme "client-go/k8s-client-go/pkg/client/clientset/versioned/scheme"
	"context"
	"time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// FirstCrdsGetter has a method to return a FirstCrdInterface.
// A group's client should implement this interface.
type FirstCrdsGetter interface {
	FirstCrds(namespace string) FirstCrdInterface
}

// FirstCrdInterface has methods to work with FirstCrd resources.
type FirstCrdInterface interface {
	Create(ctx context.Context, firstCrd *v1alpha1.FirstCrd, opts v1.CreateOptions) (*v1alpha1.FirstCrd, error)
	Update(ctx context.Context, firstCrd *v1alpha1.FirstCrd, opts v1.UpdateOptions) (*v1alpha1.FirstCrd, error)
	UpdateStatus(ctx context.Context, firstCrd *v1alpha1.FirstCrd, opts v1.UpdateOptions) (*v1alpha1.FirstCrd, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.FirstCrd, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.FirstCrdList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.FirstCrd, err error)
	FirstCrdExpansion
}

// firstCrds implements FirstCrdInterface
type firstCrds struct {
	client rest.Interface
	ns     string
}

// newFirstCrds returns a FirstCrds
func newFirstCrds(c *DummyV1alpha1Client, namespace string) *firstCrds {
	return &firstCrds{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the firstCrd, and returns the corresponding firstCrd object, and an error if there is any.
func (c *firstCrds) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.FirstCrd, err error) {
	result = &v1alpha1.FirstCrd{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("firstcrds").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of FirstCrds that match those selectors.
func (c *firstCrds) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.FirstCrdList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.FirstCrdList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("firstcrds").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested firstCrds.
func (c *firstCrds) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("firstcrds").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a firstCrd and creates it.  Returns the server's representation of the firstCrd, and an error, if there is any.
func (c *firstCrds) Create(ctx context.Context, firstCrd *v1alpha1.FirstCrd, opts v1.CreateOptions) (result *v1alpha1.FirstCrd, err error) {
	result = &v1alpha1.FirstCrd{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("firstcrds").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(firstCrd).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a firstCrd and updates it. Returns the server's representation of the firstCrd, and an error, if there is any.
func (c *firstCrds) Update(ctx context.Context, firstCrd *v1alpha1.FirstCrd, opts v1.UpdateOptions) (result *v1alpha1.FirstCrd, err error) {
	result = &v1alpha1.FirstCrd{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("firstcrds").
		Name(firstCrd.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(firstCrd).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *firstCrds) UpdateStatus(ctx context.Context, firstCrd *v1alpha1.FirstCrd, opts v1.UpdateOptions) (result *v1alpha1.FirstCrd, err error) {
	result = &v1alpha1.FirstCrd{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("firstcrds").
		Name(firstCrd.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(firstCrd).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the firstCrd and deletes it. Returns an error if one occurs.
func (c *firstCrds) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("firstcrds").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *firstCrds) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("firstcrds").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched firstCrd.
func (c *firstCrds) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.FirstCrd, err error) {
	result = &v1alpha1.FirstCrd{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("firstcrds").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
