/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "client-go/k8s-client-go/pkg/apis/dummy/v1alpha1"
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeFirstCrds implements FirstCrdInterface
type FakeFirstCrds struct {
	Fake *FakeDummyV1alpha1
	ns   string
}

var firstcrdsResource = schema.GroupVersionResource{Group: "dummy.com", Version: "v1alpha1", Resource: "firstcrds"}

var firstcrdsKind = schema.GroupVersionKind{Group: "dummy.com", Version: "v1alpha1", Kind: "FirstCrd"}

// Get takes name of the firstCrd, and returns the corresponding firstCrd object, and an error if there is any.
func (c *FakeFirstCrds) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.FirstCrd, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(firstcrdsResource, c.ns, name), &v1alpha1.FirstCrd{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.FirstCrd), err
}

// List takes label and field selectors, and returns the list of FirstCrds that match those selectors.
func (c *FakeFirstCrds) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.FirstCrdList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(firstcrdsResource, firstcrdsKind, c.ns, opts), &v1alpha1.FirstCrdList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.FirstCrdList{ListMeta: obj.(*v1alpha1.FirstCrdList).ListMeta}
	for _, item := range obj.(*v1alpha1.FirstCrdList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested firstCrds.
func (c *FakeFirstCrds) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(firstcrdsResource, c.ns, opts))

}

// Create takes the representation of a firstCrd and creates it.  Returns the server's representation of the firstCrd, and an error, if there is any.
func (c *FakeFirstCrds) Create(ctx context.Context, firstCrd *v1alpha1.FirstCrd, opts v1.CreateOptions) (result *v1alpha1.FirstCrd, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(firstcrdsResource, c.ns, firstCrd), &v1alpha1.FirstCrd{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.FirstCrd), err
}

// Update takes the representation of a firstCrd and updates it. Returns the server's representation of the firstCrd, and an error, if there is any.
func (c *FakeFirstCrds) Update(ctx context.Context, firstCrd *v1alpha1.FirstCrd, opts v1.UpdateOptions) (result *v1alpha1.FirstCrd, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(firstcrdsResource, c.ns, firstCrd), &v1alpha1.FirstCrd{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.FirstCrd), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeFirstCrds) UpdateStatus(ctx context.Context, firstCrd *v1alpha1.FirstCrd, opts v1.UpdateOptions) (*v1alpha1.FirstCrd, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(firstcrdsResource, "status", c.ns, firstCrd), &v1alpha1.FirstCrd{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.FirstCrd), err
}

// Delete takes name of the firstCrd and deletes it. Returns an error if one occurs.
func (c *FakeFirstCrds) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(firstcrdsResource, c.ns, name), &v1alpha1.FirstCrd{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeFirstCrds) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(firstcrdsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.FirstCrdList{})
	return err
}

// Patch applies the patch and returns the patched firstCrd.
func (c *FakeFirstCrds) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.FirstCrd, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(firstcrdsResource, c.ns, name, pt, data, subresources...), &v1alpha1.FirstCrd{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.FirstCrd), err
}
