/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	dummyv1alpha1 "client-go/k8s-client-go/pkg/apis/dummy/v1alpha1"
	versioned "client-go/k8s-client-go/pkg/client/clientset/versioned"
	internalinterfaces "client-go/k8s-client-go/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "client-go/k8s-client-go/pkg/client/listers/dummy/v1alpha1"
	"context"
	time "time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// FirstCrdInformer provides access to a shared informer and lister for
// FirstCrds.
type FirstCrdInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.FirstCrdLister
}

type firstCrdInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewFirstCrdInformer constructs a new informer for FirstCrd type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFirstCrdInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredFirstCrdInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredFirstCrdInformer constructs a new informer for FirstCrd type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredFirstCrdInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.DummyV1alpha1().FirstCrds(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.DummyV1alpha1().FirstCrds(namespace).Watch(context.TODO(), options)
			},
		},
		&dummyv1alpha1.FirstCrd{},
		resyncPeriod,
		indexers,
	)
}

func (f *firstCrdInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredFirstCrdInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *firstCrdInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&dummyv1alpha1.FirstCrd{}, f.defaultInformer)
}

func (f *firstCrdInformer) Lister() v1alpha1.FirstCrdLister {
	return v1alpha1.NewFirstCrdLister(f.Informer().GetIndexer())
}
